
import { GoogleGenAI, Modality, Chat } from '@google/genai';

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

function fileToGenerativePart(base64: string) {
    const mimeType = base64.substring(5, base64.indexOf(';'));
    const data = base64.substring(base64.indexOf(',') + 1);
    return {
        inlineData: {
            data,
            mimeType,
        },
    };
}

export async function generateRedesignedImage(
    imageBase64: string,
    prompt: string,
    isRefinement: boolean = false
): Promise<string> {
    const imagePart = fileToGenerativePart(imageBase64);
    
    const fullPrompt = isRefinement
        ? prompt
        : `Reimagine this room in a ${prompt} interior design style. Maintain the original room layout and architecture. Be creative but realistic.`;

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                imagePart,
                { text: fullPrompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const mimeType = part.inlineData.mimeType;
            const base64Data = part.inlineData.data;
            return `data:${mimeType};base64,${base64Data}`;
        }
    }
    
    throw new Error('No image was generated by the API.');
}

export function initializeChat(style: string): Chat {
    const systemInstruction = `You are an AI Interior Design Assistant. The user is currently viewing a room design in the '${style}' style.
If the user asks for a visual change to the image (e.g., 'make the sofa green', 'add a plant'), you MUST respond ONLY with a valid JSON object of this format: {"action": "edit_image", "prompt": "<The user's original request>"}.
If the user asks a question, for advice, or for product links, respond conversationally as an expert interior designer. Provide helpful, concise answers. If asked for products, suggest items that fit the '${style}' aesthetic and provide markdown links. Do not use JSON for these conversational answers.`;

    return ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: systemInstruction,
        },
    });
}
